[package]
name = "sux"
version = "0.1.0"
edition = "2021"
description = "A pure Rust implementation of succinct data structures from the Sux project (https://sux.di.unimi.it/)."
repository = "https://github.com/vigna/sux-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["succinct", "rank", "select"]
categories = ["compression", "data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"

[dev-dependencies]
stderrlog = "0.5.4"
log = "0.4.17"
clap = { version = "4.2.7", features = ["derive"] }
rand = {version="0.8.5", features=["small_rng"]}
dsi-progress-logger = "0.1.0"

[features]
testless_read = []
testless_write = []
