[package]
name = "sux"
version = "0.1.0"
edition = "2021"
description = "A pure Rust implementation of succinct data structures from the Sux project (https://sux.di.unimi.it/)."
repository = "https://github.com/vigna/sux-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["succinct", "rank", "select"]
categories = ["compression", "data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bitflags = "2.3.1"
bytemuck = "1.13.1"
common_traits = "0.7.0"
libc = "0.2.147"
log = "0.4.17"
mmap-rs = "0.5.0"
num_cpus = "1.16.0"
num-traits = "0.2.15"
rayon = {version="1.7.0", optional=true}
stable_deref_trait = "1.2.0"
yoke = "0.7.1"
epserde = "0.1.1"
bitvec = "1.0.1"
clap = { version = "4.2.7", features = ["derive"] }
dsi-progress-logger = "0.1.0"
stderrlog = "0.5.4"
rand = {version="0.8.5", features=["small_rng"]}
zstd = "0.12.4"
tempfile = "3.8.0"

[features]
default = ["rayon"]
